---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
      # Non modifying hooks
  - id: check-yaml
  - id: check-ast
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-toml
  - id: check-vcs-permalinks
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: debug-statements
  - id: detect-private-key
          # Modifying hooks
  - id: requirements-txt-fixer
  - id: end-of-file-fixer
    exclude: ^docs/
  - id: trailing-whitespace
    exclude: ^docs/
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.3
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0', --width, '150']

    # Update the version of python as necessary per project
    # Try to use the latest python if possible
- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
  - id: pyupgrade
    args: [--py310-plus]

    # Keep last to ensure formatting happens after all other fixes
- repo: https://github.com/psf/black
  rev: 23.10.1
  hooks:
  - id: black
    exclude: ^docs/
  - id: black-jupyter

    # Remove python notebook outputs before commit
- repo: https://github.com/kynan/nbstripout
  rev: 0.6.1
  hooks:
  - id: nbstripout
exclude: ^(.svn|CVS|.bzr|.hg|.git|__pycache__|.tox|.ipynb_checkpoints|assets|tests/assets/|venv/|.venv/)
